Improve logging
kapicorp/tesoro pull request #17
Opened 2020-08-28 14:21 UTC by bsda

Hi All, 

I've changed the format of the logs to follow a key=value format to simplify field extraction specifically in splunk (which is my use case)
I've also added the request_uid on all log entries so we can easily track a request from start to end.
And finally, I added some INFO logs and changed a couple of DEBUGs to ERROR

I'm happy to make changes if needed.

Thanks

2020-08-28 20:51 UTC, ramaro requested changes

2020-08-28 20:51 UTC, ramaro commented on tesoro/utils.py
> +        logger.error("request_id=%s Tesoro label not found", req_uid)
This should be debug, not error. Otherwise it will spam logging with objects that don't set the tesoro label

2020-08-28 20:51 UTC, ramaro commented
Thanks for this! Just a tiny thing to change, please 😃

2020-08-29 08:27 UTC, bsda commented
> Thanks for this! Just a tiny thing to change, please 😃

All done 👍

2020-08-29 16:33 UTC, uberspot approved these changes

2020-08-29 16:34 UTC, merged